#!/usr/bin/env node
/* genIcon.js — regenerates site/assets/ds/icons.css from the full icon source.
 *
 * The site ships a subset of design-system/components/icons/icon-data.js (4.6 MB,
 * the full glyph set) as CSS mask rules. This script is the only sanctioned way to
 * produce that file: it extracts each glyph's SVG body, rounds path coordinates to
 * 2 decimal places (the source carries 3, which a 24px grid cannot resolve and
 * which roughly doubles the output), wraps the body in the standard 24px viewBox
 * shell, and emits one `.sb-ico[data-ico="Name"]` rule per glyph.
 *
 * THE TRAP THIS SCRIPT EXISTS TO AVOID: the SVG markup goes into a CSS url("...")
 * string as a data URI. `<`, `>` and `"` MUST be percent-encoded (%3C %3E %22).
 * A raw double quote closes the CSS string early and the mask silently paints a
 * solid box — no console error, no 404, just a filled square where the icon
 * should be. Never hand-edit the data URIs in icons.css; change NAMES here and
 * regenerate.
 *
 * Usage:
 *   node qa/genIcon.js                     # full icons.css to stdout
 *   node qa/genIcon.js > site/assets/ds/icons.css
 *   node qa/genIcon.js Clock PlayCircle    # just those glyph rules (spot checks)
 *
 * No dependencies. Paths resolve relative to this script, so cwd does not matter.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SOURCE = path.join(ROOT, "design-system", "components", "icons", "icon-data.js");

/* The subset. Order is the emit order in icons.css. */
const NAMES = [
  "ArrowRight",
  "ChevronRight",
  "XClose",
  "Menu01",
  "LogOut01",
  "InfoCircle",
  "Scales02",
  "Users01",
  "ClipboardCheck",
  "MessageTextSquare01",
  "FileCheck02",
  "Lock01",
  "CalendarCheck01",
  "Building02",
  "CheckCircle",
  "Mail01",
  "UserCheck01",
  "Clock",
  "Podcast",
  "Route",
  "PlayCircle",
  /* v2 homepage (site-v2/) additions — 8/25 */
  "Bank",
  "Calculator",
  "Shield01",
  "PhoneCall01",
];

/* Header + base rules emitted verbatim ahead of the glyph rules. */
const HEADER = `/* Sandro Business — icon subset.
   The full set is design-system/components/icons/icon-data.js: 4.6 MB of inlined
   path data. The readme says subset before shipping, so this file carries only
   the glyphs the prototype uses.

   Each glyph is an SVG data-URI MASK painted with \`background-color:currentColor\`,
   not an <img> and not an inline <svg>. Three reasons: it inherits colour the way
   the real Icon component does, it costs no JavaScript (a glyph cannot go missing
   because a script did not run), and an SVG data-URI mask is a technique the
   readme confirms renders across every surface this system ships into. A raster
   mask is the one that does not: it fetches 200 and then silently paints the
   unmasked box.

   Coordinates are rounded to 2dp. The source carries 3, which is finer than a
   24px grid can resolve and roughly doubled this file.

   GENERATED by qa/genIcon.js. To add a glyph, add its PascalCase name to that
   script's NAMES list and rerun it (node qa/genIcon.js > site/assets/ds/icons.css).
   Do not hand-edit the data URIs, and do not reach for the 4.6 MB source at
   runtime. */
.sb-ico{display:inline-block;flex:none;width:var(--icon-md-px);height:var(--icon-md-px);
  background-color:currentColor;
  -webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;
  -webkit-mask-position:center;mask-position:center;
  -webkit-mask-size:contain;mask-size:contain}
.sb-ico[data-size="sm"]{width:var(--icon-sm-px);height:var(--icon-sm-px)}
.sb-ico[data-size="lg"]{width:var(--icon-lg-px);height:var(--icon-lg-px)}
.sb-ico[data-size="xl"]{width:28px;height:28px}
`;

/* Load the full icon set. The source is an ES module (\`export default {...}\`);
   swapping the export for a return lets plain Node evaluate it with no loader. */
function loadIconData() {
  const src = fs.readFileSync(SOURCE, "utf8");
  const body = src.replace(/^export default\b/m, "return");
  return new Function(body)();
}

/* Round one numeric token to 2dp the way the original subset was rounded: on
   the FLOAT value, half-to-even (Python `round` semantics), then drop trailing
   zeros. Not `toFixed(2)`: source tokens that are exactly representable binary
   halves (13.125, 16.125, 5.125) round to even (13.12, 16.12, 5.12), while
   tokens like 16.075 or 10.725 sit just below the half as doubles and round
   down under either rule.

   HISTORY (2026-08-14): the pre-generator icons.css was produced by two
   scratch-script eras — 25 rules rounded half-to-even, the later-appended
   PlayCircle rounded one half-token (13.125) half-up to 13.13. This generator
   implements half-to-even, and the checked-in icons.css IS its verbatim output
   (PlayCircle's token normalized to 13.12 in the same 8/14 pass, render
   re-verified) — so `node qa/genIcon.js > site/assets/ds/icons.css` is stable:
   output and file agree byte for byte, and trap 8's byte-diff proof holds on
   every glyph. */
function round2(tok) {
  const neg = tok.charAt(0) === "-";
  /* Exact decimal expansion of the double, far past 2dp; any true non-half
     shows its direction well inside 30 fraction digits. */
  const exact = Math.abs(Number(tok)).toFixed(30);
  const dot = exact.indexOf(".");
  const frac = exact.slice(dot + 1);
  let hundredths = BigInt(exact.slice(0, dot) + frac.slice(0, 2)); // value * 100
  const rest = frac.slice(2);
  const first = rest.charAt(0);
  let up;
  if (first > "5") up = true;
  else if (first < "5") up = false;
  else if (/[1-9]/.test(rest.slice(1))) up = true; // strictly above the half
  else up = hundredths % 2n === 1n; // exact half: round to even
  if (up) hundredths += 1n;
  const s = hundredths.toString().padStart(3, "0");
  let out = (s.slice(0, -2) + "." + s.slice(-2)).replace(/\.?0+$/, "");
  if (out === "" ) out = "0";
  return neg && out !== "0" ? "-" + out : out;
}

/* Round every decimal-bearing number in the SVG body (3.448 -> 3.45,
   10.379 -> 10.38, 6.900 -> 6.9). Integer tokens pass through untouched. */
function roundBody(body) {
  return body.replace(/-?\d+\.\d+/g, round2);
}

/* Percent-encode the three characters that break a CSS url("...") string.
   A raw " would close the string: the mask then silently paints a solid box. */
function encodeForDataUri(svg) {
  return svg.replace(/</g, "%3C").replace(/>/g, "%3E").replace(/"/g, "%22");
}

function glyphRule(name, entry) {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${entry.viewBox}" fill="none">` +
    roundBody(entry.body) +
    `</svg>`;
  const uri = `data:image/svg+xml,${encodeForDataUri(svg)}`;
  return `.sb-ico[data-ico="${name}"]{-webkit-mask-image:url("${uri}");mask-image:url("${uri}")}`;
}

function main() {
  const argNames = process.argv.slice(2);
  const names = argNames.length ? argNames : NAMES;
  const data = loadIconData();

  const missing = names.filter((n) => !data[n]);
  if (missing.length) {
    process.stderr.write(`genIcon.js: not in icon-data.js: ${missing.join(", ")}\n`);
    process.exit(1);
  }

  const rules = names.map((n) => glyphRule(n, data[n])).join("\n") + "\n";
  process.stdout.write(argNames.length ? rules : HEADER + rules);
}

main();
